kind: pipeline
name: OSQ

steps:
- name: QIO
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
  - qio platform install file://.
  - qio run -d examples/Arduino/bg96/bg96_i2c_Si7021
  - qio run -d examples/Arduino/bg96/bg96_dss_dns
  - qio run -d examples/Arduino/bg96/bg96_client_http

- name: PIO
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U platformio
  - pio platform install file://.
  - pio run -d examples/Arduino/bg96/bg96_i2c_Si7021
  - pio run -d examples/Arduino/bg96/bg96_dss_dns
  - pio run -d examples/Arduino/bg96/bg96_client_http


