version: 2.1
jobs:
  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "QIO"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
            qio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/Arduino/bg96/bg96_i2c_Si7021
            pio run -d examples/Arduino/bg96/bg96_dss_dns
            pio run -d examples/Arduino/bg96/bg96_client_http

  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "PIO"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/Arduino/bg96/bg96_i2c_Si7021
            pio run -d examples/Arduino/bg96/bg96_dss_dns
            pio run -d examples/Arduino/bg96/bg96_client_http

workflows:
    version: 2
    run_ci:
        jobs:
          - QIO
          - PIO

